use_frameworks!

platform :ios, '9.0'

target 'CSNetworkServices_Example' do
  pod 'CSNetworkServices', :path => '../'

  target 'CSNetworkServices_Tests' do
    inherit! :search_paths

    
  end
end
